### ISSUE TITLE
今天用不了了？

### ISSUE THREAD

**Issue by tingle0717** [atwat/bigoo#1]
能签到，能应援，就是没有辣条，还有希望能增加一个配置说明

**Comment by atwat** [comment]
> 能签到，能应援，就是没有辣条，还有希望能增加一个配置说明

改Monitor下的东西，Bilive是Vector000的bilive的监控，YjAddr和YjKey是yjqiang的bili2.0的监控，你能弄来就用，弄不来把Local和Lun改成true吧，Local是本地全区监控（每个分区各俩），Lun是轮询

**Comment by atwat** [comment]
Duplicate of #

> 能签到，能应援，就是没有辣条，还有希望能增加一个配置说明

Monitor下Bilive是bilive的监控，YjAddr/YjKey是bili2.0的监控，能搞来就用，搞不来把Local和Lun改成true。
